# Generated by Django 3.2.4 on 2022-07-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cardtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
