# Generated by Django 4.0.6 on 2022-07-17 22:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='data_price',
            field=jsonfield.fields.JSONField(),
        ),
    ]
