# Generated by Django 4.0.6 on 2022-07-17 22:36

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_verified_alter_merchant_data_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='data_price',
            field=django_jsonfield_backport.models.JSONField(),
        ),
    ]
